Month7/step1
AnnaBaraulina/react-burger pull request #1
Opened 2022-06-28 13:58 UTC by AnnaBaraulina

Пул реквест на промежуточную работу

2022-06-28 15:45 UTC, kyzinatra commented on src/components/AppHeader/AppHeader.jsx
> +                    <li className={stylesHeader.headerItem}>
Отлично! Хорошая семантика кода

2022-06-28 15:46 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +}
Надо исправить: стоит подробнее описывать этот массив указывая каждый элемент с помощью `PropTypes.shape()`

2022-06-28 15:47 UTC, kyzinatra commented on src/App.jsx
> +        <BurgerConstractor/>
Отлично! Очень хорошая реализация `<BurgerIngredients/>`

2022-06-28 15:50 UTC, kyzinatra commented on src/components/BurgerConstructor/BurgerConstructor.jsx
> +                <DragIcon/>
Надо исправить: тут лучше в качестве key использовать индекс элемента. Так как в конструкторе может быть несколько одних и техже элементов.  В следующих спринтах вы будете генерировать его 1 раз при добавлении в конструктов, а пока испоьлзуейте просто индекс массива

2022-06-28 15:53 UTC, kyzinatra requested changes
Выглядит очень круто! Видно, что проделана большая работа.

Что важно исправить:

- app.jsx стоит внести в отдельную папку
- Стоит типизировать props более подробно

Можно лучше:

- Отступ сверху у header стоит убрать. В дизайне его нет

Что понравилось:

- Хорошая семантика кода
- Хорошая реализация компонентов. Работа выполнена аккуратно

2022-06-29 14:14 UTC, kyzinatra commented
Привет, мне уже написали. Сейчас решим этот вопрос)

2022-06-29 14:34 UTC, kyzinatra commented on src/components/BurgerIngredients/BurgerIngredients.jsx
> +
Можно лучше: Стоит также описывать это типы при помощи .shape
Подробнее про proptypes
https://www.npmjs.com/package/prop-types

2022-06-29 14:53 UTC, AnnaBaraulina commented
Спасибо большое!

2022-06-29 14:56 UTC, merged